package protocol.core;

public enum PacketType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,

    CHAT_MESSAGE,
    CONTROL_SIGNAL,
    CLIPBOARD_DATA,
    FILE_REQ,
    FILE_CHUNK,
    FILE_OFFER,
    FILE_ACCEPT,
    CONNECT_REQUEST,
    CONNECT_RESPONSE,
    START_STREAM,
    DISCONNECT_NOTICE,
    AUDIO_DATA,
    PEER_INFO,
    PEER_REGISTER,
    P2P_HELLO
}